services:
  ecommerce-gateway-postgres:
    image: postgres:18
    container_name: ecommerce-gateway-postgres
    restart: always
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: gatewaydb
    ports:
      - "5400:5432"
    volumes:
      - gateway-postgres-data:/var/lib/postgresql

  ecommerce-inventory-postgres:
    image: postgres:18
    container_name: ecommerce-inventory-postgres
    restart: always
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      POSTGRES_DB: inventorydb
    ports:
      - "5401:5432"
    volumes:
      - inventory-postgres-data:/var/lib/postgresql

  ecommerce-sales-postgres:
    image: postgres:18
    container_name: ecommerce-sales-postgres
    restart: always
    environment:
      POSTGRES_USER: sales
      POSTGRES_PASSWORD: sales
      POSTGRES_DB: salesdb
    ports:
      - "5402:5432"
    volumes:
      - sales-postgres-data:/var/lib/postgresql

  ecommerce-rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  gateway-postgres-data:
  inventory-postgres-data:
  sales-postgres-data:
